server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:hello-querydsl;
    driver-class-name: org.h2.Driver
    username: abc
    password: abc
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none